import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import {
  SidebarProvider,
  Sidebar,
  SidebarHeader,
  SidebarContent,
  SidebarInset,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { LogoIcon } from "@/components/icons/logo-icon";
import MainNavLinks from "@/components/main-nav-links";
import { Button } from "@/components/ui/button"; // Added for potential future use
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "InvestPro",
  description: "Generated by Firebase Studio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={cn(
          "font-body antialiased",
          process.env.NODE_ENV === "development" ? "debug-screens" : undefined
        )}
      >
        <SidebarProvider defaultOpen={true}>
          <Sidebar collapsible="icon" className="hidden md:flex">
            <SidebarHeader>
              <div className="flex items-center gap-2 p-4">
                <LogoIcon className="h-8 w-8 text-primary" />
                <span className="font-semibold text-lg group-data-[collapsible=icon]:hidden font-headline">
                  InvestPro
                </span>
              </div>
            </SidebarHeader>
            <SidebarContent>
              <MainNavLinks />
            </SidebarContent>
          </Sidebar>
          <div className="flex flex-col flex-1 min-h-screen">
            <header className="sticky top-0 z-10 flex h-14 items-center justify-between gap-4 border-b bg-background px-4 sm:px-6 md:hidden">
              <div className="flex items-center gap-2">
                <LogoIcon className="h-7 w-7 text-primary" />
                <span className="font-semibold text-md font-headline">
                  InvestPro
                </span>
              </div>
              <SidebarTrigger />{" "}
              {/* This trigger is for mobile, controlled by SidebarProvider */}
            </header>
            <SidebarInset>
              <main className="flex-1 p-4 sm:p-6">{children}</main>
            </SidebarInset>
          </div>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
